services:
  goodhamburger-api:
    build:
      context: .
      dockerfile: src/GoodHamburger.API/Dockerfile
    container_name: goodhamburger-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Data Source=/app/data/goodhamburger.db
      Cors__AllowedOrigins__0: http://localhost:5200
      Cors__AllowedOrigins__1: https://localhost:7200
    ports:
      - "5000:8080"
    volumes:
      - goodhamburger_data:/app/data

  goodhamburger-web:
    build:
      context: .
      dockerfile: src/GoodHamburger.Web/Dockerfile
    container_name: goodhamburger-web
    depends_on:
      - goodhamburger-api
    ports:
      - "5200:80"

volumes:
  goodhamburger_data:
